#!/bin/bash

#
# CBRAIN Project
#
# Copyright (C) 2008-2025
# The Royal Institution for the Advancement of Learning
# McGill University
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#########################
# S U B R O U T I N E S #
#########################

# Usage
function usage {
  echo "Usage: $0 xxxxx"
  exit 10
}

# Fatal error message
function fatal {
  echo "$*"
  exit 20
}

# Print usage if zero args, or -h or --help
if test $# -eq 0 -o "X$1" = "-h" -o "X$1" = "--help" ; then
  usage
fi

# Make sure we have all 5 args
if test $# -ne 5 ; then
  fatal "This program requires 5 arguments. See --help ."
fi

# This program only works if its CWD is the Bourreau's root dir.
# We verify this by checking for the presence of a particular file.
if ! test -f "app/models/bourreau_worker.rb" ; then
  fatal "This program '$0' must be started from the Bourreau directory."
fi

# Positional arguments
user="$1"
host="$2"
port="$3"
dbspec="$4"
sshagentspec="$5"

# Run-time paths and names of host and program
basename=$(basename $0)   # not used yet
curhost=$(hostname -s)    # not used yet
rails_home=$(realpath $PWD)

# Local socket names that we will establish here
database_sock="$rails_home"/tmp/sockets/db.reverse.sock
sshagent_sock="$rails_home"/tmp/sockets/ssh_agent.sock

# TMP; handle better in future
rm -f "$database_sock" "$sshagent_sock"

# Start the main SSH tunnel back to the service host
ssh -q -n -N -x -f -p "$port" "$user@$host" \
  -o ForwardAgent=No                        \
  -o ForwardX11=No                          \
  -o ExitOnForwardFailure=Yes               \
  -L "$database_sock":"$dbspec"             \
  -L "$sshagent_sock":"$sshagentspec"

status=$?
if test $status -ne 0 ; then
  fatal "Failed to start SSH connection back to CBRAIN service host"
fi

echo "CBRAIN Reverse SSH Started" # this sentence is checked by the portal
exit 0

