#!/bin/bash

#
# CBRAIN Project
#
# Copyright (C) 2008-2025
# The Royal Institution for the Advancement of Learning
# McGill University
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#########################
# S U B R O U T I N E S #
#########################

# Usage
function usage {
  echo "Usage: $0 xxxxx"
  exit 10
}

# Fatal error message
function fatal {
  echo "$*"
  exit 20
}

# This program only works if its CWD is the Bourreau's root dir.
# We verify this by checking for the presence of a particular file
if ! test -f "app/models/bourreau_worker.rb" ; then
  fatal "This program '$0' must be started from the Bourreau directory."
fi

# Run-time paths and names of host and program
basename=$(basename $0)
curhost=$(hostname -s)
rails_home=$PWD

# hardcoded name for the moment; must be configured in .ssh/config
ssh -q -n -N -x -f cbrain_services || echo "Failed to start SSH connection back to CBRAIN service host" && exit 20

echo "CBRAIN Reverse SSH Started" # this sentence is checked by the portal
exit 0

