
#
# CBRAIN Project
#
# Copyright (C) 2008-2026
# The Royal Institution for the Advancement of Learning
# McGill University
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

source 'https://rubygems.org'

#----------------------
# In the :default group
#----------------------

# Network components mostly
gem "net-ssh",       :require => 'net/ssh'
gem "net-sftp",      :require => 'net/sftp'
gem "x25519"
gem "ed25519"
gem "bcrypt_pbkdf"
# You can comment-out the following two gems if you don't mind not having 'userkey' data providers.
# They are usually the most tricky to compile and integrate into the app.
gem "rbnacl"
gem "rbnacl-libsodium"

# Other utilities
gem "sys-proctable"
gem 'mysql2'
gem "pbkdf2-ruby"
gem "json-schema"
gem "aws-sdk-s3"
gem 'zenodo_client', '>= 1.0.0', :git => 'https://github.com/aces/zenodo-client-gem'
gem 'jwt', ">= 3.0.0"
gem 'shannon'
gem "rack-cors"
gem 'csv'

# User interface gems
gem "will_paginate"
gem 'pagy', '~>3.7'   # fast pagination for NeuroHub
gem "jquery-rails"
gem "jquery-ui-rails"
gem "jquery-form-rails"

# ActiveResource channel gems
gem "activeresource", require: 'active_resource'
gem "actionpack-xml_parser"
gem "activemodel-serializers-xml"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.1.3"
gem 'sprockets-rails', :require => 'sprockets/railtie'
gem 'sassc-rails' # "rake assets:precompile" fails if this gems is put into the :assets group

# Use sqlite3 as the database for Active Record
#gem "sqlite3", ">= 2.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
#gem "stimulus-rails"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
#gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
#gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"

#----------------------
# Assets
#----------------------

gem 'coffee-rails'
gem 'uglifier'

#----------------------
# Development+Test
#----------------------

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Audits gems for known security defects (use config/bundler-audit.yml to ignore issues)
  gem "bundler-audit", require: false

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end

#----------------------
# Development
#----------------------

group :development do
  gem "looksee"
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

#----------------------
# Test
#----------------------

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end

