
#
# CBRAIN Project
#
# Copyright (C) 2008-2012
# The Royal Institution for the Advancement of Learning
# McGill University
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

source 'https://rubygems.org'

#----------------------
# In the :default group
#----------------------

gem "rails", "~> 8.1.3"

# Network components mostly
gem "net-ssh",       :require => 'net/ssh'
gem "net-sftp",      :require => 'net/sftp'
gem "x25519"
gem "ed25519"
gem "bcrypt_pbkdf"
# You can comment-out the following two gems if you don't mind not having 'userkey' data providers.
# They are usually the most tricky to compile and integrate into the app.
gem "rbnacl"
gem "rbnacl-libsodium"

# Other utilities
gem "sys-proctable"
gem "mysql2"
gem "pbkdf2-ruby"
gem "json-schema"
gem "aws-sdk-s3"
gem "jwt", ">= 3.0.0"
gem "shannon"
gem "csv"

# ActiveResource channel gems
gem "activeresource", require: "active_resource"
gem "actionpack-xml_parser"
gem "activemodel-serializers-xml"

#----------------------
# Test
#----------------------

group :test do
  gem "rspec"
  gem "rspec-rails"
  gem "factory_bot",       '6.4.2', :require => false
  gem "factory_bot_rails", '6.4.2', :require => false
  gem "rails-controller-testing"
  gem "rspec-mocks"
  gem "rspec-activemodel-mocks"
  gem "rspec-collection_matchers"
  gem "database_cleaner"
end

